### ISSUE TITLE
Kubernetes dashboard 可以登入，但一直报 XXX is forbidden

### ISSUE THREAD

**Issue by kevinanew** [opsnull/follow-me-install-kubernetes-cluster#201]
```
# kubectl version --short
Client Version: v1.8.4+coreos.0
Server Version: v1.8.4+coreos.0
```

我登录dashboard 后，就看到这一堆的错误
```
configmaps is forbidden: User "system:serviceaccount:kube-system:admin-user" cannot list configmaps in the namespace "kube-system"

persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:admin-user" cannot list persistentvolumeclaims in the namespace "kube-system"

secrets is forbidden: User "system:serviceaccount:kube-system:admin-user" cannot list secrets in the namespace "kube-system"

services is forbidden: User "system:serviceaccount:kube-system:admin-user" cannot list services in the namespace "kube-system"

ingresses.extensions is forbidden: User "system:serviceaccount:kube-system:admin-user" cannot list ingresses.extensions in the namespace "kube-system"
....
```

admin-user 的创建如下：

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
```

错误提示感觉是RBAC的权限导致的，但我已经给了 cluster-admin ，很迷惑。
