### ISSUE TITLE
kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap 报错

### ISSUE THREAD

**Issue by liz1989** [opsnull/follow-me-install-kubernetes-cluster#26]
我跟着教程安装k8s，执行到
```kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap```
总是报错
Error from server (Forbidden): User "admin" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope. (post clusterrolebindings.rbac.authorization.k8s.io)

**Comment by opsnull** [comment]
> Error from server (Forbidden): User "admin" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope. (post clusterrolebindings.rbac.authorization.k8s.io)

看起来你的 kubectl 使用的 ~/.kube/config 文件有问题，请确认下是否嵌入了 `02-创建TLS证书和秘钥.md` 步骤创建的 admin 证书。

**Comment by liz1989** [comment]
检查了好几遍，确实是按照`02-创建TLS证书和秘钥.md 步骤`创建的证书。
这是我的`~/.kube/config `
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVSDRuVTJ1aWlPK00zUlJvbWNGL2t0Zzh1WDJvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjA1aGJtcHBibWN4RURBT0JnTlZCQWNUQjBwcApZVzVuYzNVeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTURReE9EQTFORFV3TUZvWERUSXlNRFF4TnpBMU5EVXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjA1aGJtcHBibWN4RURBT0JnTlZCQWNUQjBwcFlXNW5jM1V4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdzBPcll3cVFVOWZicmNYSHUxZ0UKY0NTR3gwbXNyU0JuQlAyWWtTZFhseHhsOFZDWDZGdGcrOExkYXZuTmZJSjZOdnpRb0pObWJhcXZTc0VWV0pDeApiVHpJNUl6V0NaWDdEdzQvaWZBUXlSNWVjNllwT0RsaTl3RkUyVTMvb2FtV3RkUXY5WU53SGFtVHltVFdpZTNrClQ2TDV1cGNodXpWTEFEWVZOUjh4Ulk1WXFkako5T2l1Q3NsNWw4RVhjS1N4UXYzTE9IMUN0ZzZ1ckxBYXBEQjMKVlptc0hyVzh0RnZVR0kyUkN4T3RoV013bHJxTGdvYXB0YWtIT05jTkozakI0alBrL2NwR0JDTnVSOW9ySGs3eQo1ak1SUnJsdDB5cUdGazdSZlZMdXJYOE9LdWFsUGFQUlk5V3FsdU1neXg3YUVGRzB4QWxNbVY0VlRxanNLc0FwCmp3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVOTJOWk52SlgxMGxxRVNGZStzVmxYMGxtbFhvd0h3WURWUjBqQkJnd0ZvQVU5Mk5aTnZKWAoxMGxxRVNGZStzVmxYMGxtbFhvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDTml3cEVEbUJiN3F5bStBU2xJCjBEcWtDNDgvUXk1Q1ZieTN3UUVnSnJJUU4wd2lrcTF2cmFid1NMNExUZVVsNi9KVEdqTjczQThXcWxsclNyWW4Ka1pKT25HcE9FQ2RCT3B5WU53RmR3ckQ2UCtpQ01GbTN4WE0wMWhsOVp4MmNHUERsYThUTERjVC9NTGprNlh4RQppa1NzaU1XRXRZSmJkSDZXUWs1VHZxUzJpWWZlL3FIU0ZiUjdQb1pITFczZ3V1eXNySEFXOW5kV0JWS21aclBzClI0VGRTTlVCMXVDZUsvQ0xUTVE1eFhKK2xua0lxUmhSRVFLTVZTVFFUOGovZkJWd0h6R3pFaDU4TkYrRkN4Y2MKQXErazdyN0Jkd3U1YUdXaXhINjNmZ254RUFPK0txd082M3d2VmQ0VTcxcHR6NDh0dVN3TGtpWHl6V1Ivc2lMUwozb2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.137.32.32:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwakNDQXJxZ0F3SUJBZ0lVYnhKT2RZVGVqMnRzREJ0YXZKRXg4ZDVLNW5Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjA1aGJtcHBibWN4RURBT0JnTlZCQWNUQjBwcApZVzVuYzNVeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTURReE9EQTNORFV3TUZvWERURTRNRFF4T0RBM05EVXdNRm93WURFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjA1aGJtcHBibWN4RURBT0JnTlZCQWNUQjBwcFlXNW5jM1V4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUTR3REFZRFZRUURFd1ZoWkcxcGJqQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLWXhoc2Z1TnhqZGMrMURJN3VFMFJzd1BMSmwKcU5kWEEveVZHdlRWVktUMXo2d240a2JZbGRMWTlsTzFHOTFqaENqdU02allsV2ZBWk1GdG5HTkZoZTlCTnIvVgpldzJzRkN0akZIMDladFZSVGs4U2NWTEhma3F6MzJLTTRUMGlWdGZIOWg4ZWplUEtVODdvamNBa2NyRFJNR1piCmdaMnptUWhCeDNka3B0V1hxWXBpckJyR1pZeHNnUFdBZnBsZ2FLZzFpNFp6cjQ3Q3pEVjNYd3dNdjRUamVXTTQKVjVFV3p4OGN2UHhrdVNjOFRyZHZweUUwSzJmdGFmcnhsSi92OHoreDJNTFI5N21GRGF6WDNrdUpOWU5kVU90dQoyQ3BlbElKREZ5ay9jSU9uKzZpRGdKb2dUWldMWktWSGpvbGpjRkdURTRCUmUzSlpjWldOQ3FINTYzOENBd0VBCkFhTi9NSDB3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTV3Y0WlM3VG1GaDFEYkhQVVgzWmZLWnE5NQoyREFmQmdOVkhTTUVHREFXZ0JUM1kxazI4bGZYU1dvUklWNzZ4V1ZmU1dhVmVqQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBWURRVFhxa24zNGhhVld5RHZYTFZhWWtDYzdmVWRjRWxheWVjQWVrNHJSZ2hoRk9NRjgwY0ZseUwKSnI2VWlLbUJHTmNocGZvOEdOVDIzS1JUTWU1TW9pUmxYaHp0bTcrWVV6RnVQS0xVbHk1SGtJY1JlNEpKOGs5MgpzbkQzSFYyRU12eXJVNnV0UFc4K1pvMTVMOFRvZHJjallKY2xTNmNwWEYzUUVnRTA5azJqbmhETHFNNERRanVMCkRJQVg1eDFORGJzQlRhRC90cWlPQUV6U3hHWHRYdlZ5NzEwTFBBQ0pTMVZmdVdDbGRYV056QlRzcW5LZVFoU2wKdXorSlhCM0RkbldmYmJndTZuN3BRSUVYbDdNNjcrVFFFdzIxdjd5Si9TdDhDTlE4M1NyK3g2bDNrQTlwQUZKQwo3eUZCbGY1N0tEakZldVpSbTNGUGMvaUhhT3dER3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcGpHR3grNDNHTjF6N1VNanU0VFJHekE4c21XbzExY0QvSlVhOU5WVXBQWFByQ2ZpClJ0aVYwdGoyVTdVYjNXT0VLTzR6cU5pVlo4Qmt3VzJjWTBXRjcwRTJ2OVY3RGF3VUsyTVVmVDFtMVZGT1R4SngKVXNkK1NyUGZZb3poUFNKVzE4ZjJIeDZONDhwVHp1aU53Q1J5c05Fd1psdUJuYk9aQ0VISGQyU20xWmVwaW1LcwpHc1psakd5QTlZQittV0JvcURXTGhuT3Zqc0xNTlhkZkRBeS9oT041WXpoWGtSYlBIeHk4L0dTNUp6eE90MituCklUUXJaKzFwK3ZHVW4rL3pQN0hZd3RIM3VZVU5yTmZlUzRrMWcxMVE2MjdZS2w2VWdrTVhLVDl3ZzZmN3FJT0EKbWlCTmxZdGtwVWVPaVdOd1VaTVRnRkY3Y2xseGxZMEtvZm5yZndJREFRQUJBb0lCQUNnb2Q0VUFEdGczU3JmZQpMVmcyYzhDNkd6Q1FXQWdRd3FuWjdiV1RodXlGYVRVVVBoMFlZTHVlS1lkNGo4OGpLT0FyRHRpUjNTaEEyUmZVClFLSE1QdHpkU1RsNWdFNkJjaTQ1dHMyOGRJaS9LTWo2ajkrTXpQdUlFMFpnL0Z3bFhBNndCc3ptT1NyOXpOcUcKWHhvNnRHdjlZRkNiYytxRFowc1RlZnRqbXR5cGNXSzJkQ3ZSRlNBMDlIMTdQL2JYQjRqTStuTGpDT2YyaDZkawovVVNBME9oVWR5S2EzMnIwUE1yeTdZeU9PMXloY0dKVGZXa1BXeENvVU9BQm9uWDkrQ3JGdVlDdUllK2YrTUZ4Ckh2RTBKVXJTNklDWXljdzMrMk9oLzV0c2tmK2pRVFhuNkp0ZFFzRGMraXJEbjJiUmF1MEliWGMwRDVPcTBrZXcKcG40Qkw0RUNnWUVBek44SFFCbmhsVWtBd24yQjM3b3VBajcrdHFmMFBSZkkvaDdzMk5BaTlhU3FVa0RNTmlYQQpFVUxkSzNUVld6TWdwbkJ5YVBoUklyMHFTNW5sVVA5K2N0OXRkeHpuY3Vqd3dSYlQ0NXk3N0VZSmQxN25kcFZ3ClQ3VDNtU0VZR2o3QVhYM0lkRFB5MWRTNzN3S1M4QlY2QlJwZ0dxOVBoTjdNVjVmWit1aC82VzhDZ1lFQXo2dHMKbytadExCQk51cTNNV3E3NWhlZU9sMC8xQWVjc3cvZzBNRlowdWVLNUVJUjd2d21qa0t5WXFtN2N4UXRmcW90VwovOEJRa2hORWEyTWtKa2FlcW5XajBid0pZcVQzT2lKZVBnWWNoYmRIUUY3cnN2blhNTU0vN2hISkdhMUFFQldBCno3RkpHL1piRkhyWUpnTGVORFp2QU5jd3pIdzcyb1FtbEJ4cWR2RUNnWUJHQzQ4SURKRkRJRVdoT1pZWTd5ZmgKM3JYcHIzempFbW5HOEwzYjF6WE10TE1ERW1KL3RPSjVSRm9vREhjU0NtWUVZZmZNQ2ZKN3BSOTczNjgyeFZQdgpaSktob2dGRUdYNlBGZ1gyRVZWekQvTVduQjBaUHppNkY4NTd6WVBYSFZOWjQ3S1FnRjVyVzZPc09NNFNSZFdGClB5SlNuVlBid3Uwc21aK09tTVY3QXdLQmdGVEJGcjZ4blY2OWJLdkNvTU5sNUFwbFhjbWRaVllZZmltZzA5UGkKaFJNVVdBbEl1S1JZRDd4TTVLV3lSMEhZQ1h3MkVCU2k3WDhnZyt6NzhsWDR2bXE5UmxXajA0VEI1UENCOUVxRgovZ0FJcy9pdWhLMXYwQVpqdVdTMU40aldMMjRoQ0lnN1I2WTAzaWsybFo2MXp2QXFReFZwdmMzRzZqcWRjbzFDCko2VlJBb0dBSENaMVdMOTAxT3p4MEdGNm43YVlZbVdib2prcFR6dXB6ZWJMdE1KZGlwL1ZIMlRRbGxvd0c0a2MKTGx5eGlQQ2pkekN0TlV5SGxVemhJYlVTSWxUT2VnSnpJSnR1czUxSGV5cGdybjFRL1J2MklhS0ZlQUJ4SExMTAo0eFE3b1JmN1pHMzFkbXdyMk9KZERvUHNCQjYvMk4vOGN4REtJSU1XTWhDRXhWUlVpZFU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```
