### ISSUE TITLE
kubectl logs 和 kubectl exec 执行问题

### ISSUE THREAD

**Issue by yaxu666** [opsnull/follow-me-install-kubernetes-cluster#278]
### 背景
我已经参照文档把cluster搭建起来了，`08.验证集群功能`已经验证通过了。

### 问题
然后我在做其他测试的时候用到了 `kubectl logs` 和 `kubectl exec`这两个命令，居然提示有错误：
`Error from server (Forbidden): Forbidden (user=kubernetes, verb=get, resource=nodes, subresource=proxy) ( pods/log nginx-ds-bj999)`，从错误提示看，是`kubernetes`用户没有权限。

那么问题来了，我的kubeconfig中明明是用的admin：
```
... ...
contexts:
- context:
    cluster: kubernetes-cl
    user: admin
  name: kubernetes-c
current-context: kubernetes-c
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: ... ...
```

### 继续研究
因为错误提示是kubernetes用户没有权限，所以我又创建了一个clusterrolebinding，给kubernetes用户赋了cluster-admin角色，结果就可以了。

### 所以现在困惑的问题是：为什么执行kubectl用的config中明明只有一个user admin，最后执行的时候apiserver却返回告诉我说我的user kubernertes没权限？
