### ISSUE TITLE
配置kubedns后，请求集群外部http资源相应慢

### ISSUE THREAD

**Issue by liyongzhezz** [opsnull/follow-me-install-kubernetes-cluster#345]
我在集群内部署kubedns，configmap如下：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  upstreamNameservers: |
    ["10.33.1.251", "10.33.1.84", "10.33.1.108"]
```

然后在pod中请求器群外部接口的时候相应很慢，例如：
- 在集群内pod中请求：
```
[root@centos /]# time curl www.baidu.com
real	0m5.533s
user	0m0.004s
sys	0m0.006s
```

- 在集群外请求：
```
time curl www.baidu.com
real	0m0.023s
user	0m0.003s
sys	0m0.005s
```

请问这可能是什么原因？如何排查及解决？ @opsnull
