### ISSUE TITLE
关于部署高可用 kubernetes master 集群的问题

### ISSUE THREAD

**Issue by rootsongjc** [opsnull/follow-me-install-kubernetes-cluster#4]
**环境**
- CentOS 7.2.1511
- Docker 1.12.5
- Kubernetes 1.6.0

**问题描述**

我按照**部署高可用 kubernetes master 集群**文档部署的master节点，不过改了一些配置文件，但是步骤是一样的，最后有如下几个现象，我认为可能是TLS还有问题。我看不出来究竟是哪里的问题，这是我的整个[操作步骤](https://github.com/rootsongjc/follow-me-install-kubernetes-cluster/blob/master/05-%E9%83%A8%E7%BD%B2%E9%AB%98%E5%8F%AF%E7%94%A8master%E9%9B%86%E7%BE%A4.md)。

**现象一**

kubectl get componentstatuses时有有如下报错信息：
```
    etcd-2               Unhealthy   Get http://172.20.0.113:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02" 
```
与TLS认证有关。

**现象二**

kube-apiserver启动时有报错信息；

```
    Apr 11 18:06:25 sz-pg-oam-docker-test-001.tendcloud.com kube-apiserver[25718]: E0411 18:06:25.522715   25718 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.ResourceQuota: the server cannot complete the requested operation at this time, try again later (get resourcequotas)
    Apr 11 18:06:25 sz-pg-oam-docker-test-001.tendcloud.com kube-apiserver[25718]: E0411 18:06:25.951292   25718 storage_rbac.go:140] unable to initialize clusterroles: the server cannot complete the requested operation at this time, try again later (get clusterroles.rbac.authorization.k8s.io)
```

这个错误是否影响kubernentes运行？

**现象三**

kubectl get命令无法正常使用。

    $kubectl --kubeconfig ~/.kube/config get all
    Unable to connect to the server: unexpected EOF
    The connection to the server 172.20.0.113:6443 was refused - did you specify the right host or port?
    The connection to the server 172.20.0.113:6443 was refused - did you specify the right host or port?

查看config。

```
    apiVersion: v1
    clusters:
    - cluster:
        server: http://sz-pg-oam-docker-test-001:8080
      name: default-cluster
    - cluster:
        certificate-authority-data: REDACTED
        server: https://172.20.0.113:6443
      name: kubernetes
    contexts:
    - context:
        cluster: default-cluster
        user: default-admin
      name: default-context
    - context:
        cluster: kubernetes
        user: admin
      name: kubernetes
    current-context: kubernetes
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: REDACTED
        client-key-data: REDACTED
```
而~/.kube/config文件也存在，6443端口也在，为什么无法访问？
