### ISSUE TITLE
部署 metrics-server 插件：可以取消授予 kube-system:metrics-server ServiceAccount 访问 kubelet API 的权限

### ISSUE THREAD

**Issue by marvinpan8** [opsnull/follow-me-install-kubernetes-cluster#410]
部署 metrics-server 插件：可以取消授予 kube-system:metrics-server ServiceAccount 访问 ，也可以正常部署
```
 cat << EOF|tee auth-kubelet.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server:system:kubelet-api-admin
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
EOF
```
