### ISSUE TITLE
通过 kube-apiserver 访问dashboard，提示User "system:anonymous" cannot proxy services in the namespace "kube-system".

### ISSUE THREAD

**Issue by ipchy** [opsnull/follow-me-install-kubernetes-cluster#5]
``` bash
[root@master1 ~]# kubectl cluster-info
Kubernetes master is running at https://192.168.6.212:6443
KubeDNS is running at https://192.168.6.212:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.6.212:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
使用浏览器访问https://192.168.6.212:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard，在浏览器钟提示
``` html
User "system:anonymous" cannot proxy services in the namespace "kube-system".
```
通过访问http://NodeIP:nodePort是能够访问的,通过kubectl proxy也可以访问，请问是不是还需要其他的配置什么的

**Comment by rootsongjc** [comment]
+1 我也遇到了这个问题，给电脑倒入了证书，可以通过https认证了，但是身份又有问题。
访问`master:8086/ui`时候的报错
```
 Forbidden (403)

User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default". (get jobs.batch)
```
使用浏览器访问http://NodeIP:nodePort也报这个错误。

**Comment by ipchy** [comment]
@rootsongjc 你这个错误貌似是RBAC授权导致的吧，看看这个是不是你需要的https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/08-dashboard-addon.md

**Comment by opsnull** [comment]
@ipchy 
> 使用浏览器访问https://192.168.6.212:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard，在浏览器钟提示
>
> User "system:anonymous" cannot proxy services in the namespace "kube-system".

出现这种错误，是由于浏览器使用匿名证书访问 kube-apiserver 安全端口， RBAC  授权失败；

如 @rootsongjc 的建议，可以导入admin 证书来访问这个URL，admin证书中的 "O": "system:masters" 字段会通过 RBAC 授权；

**Comment by opsnull** [comment]
@rootsongjc 
> Forbidden (403)
>
> User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default". (get jobs.batch)

参考最新文档，昨晚fix了这个问题。

**Comment by rootsongjc** [comment]
@ipchy @opsnull 谢谢二位，问题解决了，确实是因为rbac的问题。但是访问https://master:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard报错的问题依然没有解决。

**Comment by opsnull** [comment]
@rootsongjc  访问 kube-apiserver  安全端口需要给浏览器提供一个能通过 RBAC 授权的证书(如 admin 证书)，可以参考制作 admin 证书的步骤，制作一个客户端证书，导入浏览器，确保访问 https://kube-apiserver:6443 使用这个证书即可。

**Comment by opsnull** [comment]
BTW, 我更新了文档，使用 kube-apiserver 的非安全端口访问服务；

**Comment by ipchy** [comment]
@rootsongjc 你不是解决了么？将证书导入到计算机之后就可以了啊，如果还不可以就重启一下浏览器，在操作过程中貌似需要将pem格式转换一下，我是转换成p12格式的
``` bash
# 这个是开始存放证书的目录，依你设置的为主
cd /root/ssl
openssl pkcs12 -export -in admin.pem  -out admin.p12 -inkey admin-key.pem
``` 
然后将admin.p12文件down下来，导入到计算机钟就可以了，在转换过程中可以配置一个密码，我留空的，再导入的时候需要使用这个密码，希望能解决你的问题

**Comment by rootsongjc** [comment]
@ipchy thanks，问题解决。

**Comment by gabencui** [comment]
我是用kubeadm安装的集群，上面提到的admin证书，与我机器上哪个证书是对应的呢？
[root@k8s-master ~]# ls /etc/kubernetes/pki/
apiserver.crt  apiserver-kubelet-client.crt  ca.crt  front-proxy-ca.crt  front-proxy-client.crt  sa.key
apiserver.key  apiserver-kubelet-client.key  ca.key  front-proxy-ca.key  front-proxy-client.key  sa.pub

**Comment by opsnull** [comment]
@gabencui  上面提到的 admin 证书是二进制安装前生成的，不适用于 kubeadm 安装的集群。

**Comment by gabencui** [comment]
@opsnull ok

**Comment by yangchuansheng** [comment]
@ipchy 我能问一下证书是怎么导入的吗，linux系统

**Comment by xiajohnnyxia** [comment]
请问容器中如果要访问的话怎么办，比如Heapster只能访问非安全接口。 不然会无限重启

**Comment by dxg0716** [comment]
这个证书怎么导入到自己电脑上啊，我导入了但是访问还是会出现不安全的警告

**Comment by Ymylovely** [comment]
@opsnull 请问一下kubeadm安装的应该怎么通过dashboard的授权呢？

**Comment by liangazhou** [comment]
同楼上问

**Comment by RainingNight** [comment]
跪求，kubeadm安装的怎么在外网访问Dashboard？

**Comment by zizhazhu** [comment]
@Ymylovely 可以自己生成秘钥和证书，然后用kubeadm提供的根证书签名，就可以生成p12格式的证书了。
可以参考 https://github.com/xizhibei/blog/issues/64

**Comment by Ivan-yyq** [comment]
访问https://192.168.0.233:6443/api/v1/namespaces/default/pods
出现以下问题：
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "pods is forbidden: User \"system:anonymous\" cannot list pods in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "kind": "pods"
  },
  "code": 403
}
请问是什么原因导致的？

**Comment by RainingNight** [comment]
同问 @Ivan-yyq

**Comment by Ivan-yyq** [comment]
> 同问 @Ivan-yyq

k8s访问https都会出现403，证书是部署k8s自动配置的

**Comment by Ivan-yyq** [comment]
@RainingNight 
k8s访问https都会出现403，证书是部署k8s自动配置的

**Comment by RainingNight** [comment]
@Ivan-yyq 怎么解决呢？

**Comment by Ivan-yyq** [comment]
解决了，我服务器没配置证书服务




联系人：杨远强
电话：15625087150
邮箱：15625087150@163.com
在2018年11月14日 20:42，RainingNight 写道：

@Ivan-yyq 怎么解决呢？

**Comment by 1391518** [comment]
- 在kubernetes-dashboard.yaml配置文件后, 增加如下代码. 然后重建一下dashboard就行.
```
---
# ------------------- Gross Hack For anonymous auth through api proxy ------------------- #
# Allows users to reach login page and other proxied dashboard URLs
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-dashboard-anonymous
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["https:kubernetes-dashboard:"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- nonResourceURLs: ["/ui", "/ui/*", "/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dashboard-anonymous
subjects:
- kind: User
  name: system:anonymous
```
